services:
- type: web
  name: renderdeploy
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn renderdeploy.wsgi:application
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: renderdeploy
        property: connectionString
    # - key: DJANGO_SECRET_KEY
    - key: SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: renderdeploy.settings.production
